# Codecov configuration to make it a bit less noisy
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 50%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: default
  flags: null
  paths: null
ignore:
  - "psiresp/due.py"
  - "psiresp/tests"
  - "psiresp/_version.py"
fixes:
  - "/home/circleci/::"
