# Configure LGTM for this package
queries:
  - exclude:  py/procedure-return-value-used  # blame duecredit
  - exclude:  py/missing-equals  # subclasses of Model tend to trigger this
extraction:
  python:  # Configure Python
    python_setup:  # Configure the setup
      version: 3  # Specify Version 3
path_classifiers:
  library:
    - versioneer.py  # Set Versioneer.py to an external "library" (3rd party code)
    - devtools/*
  generated:
    - psiresp/_version.py
  test:
    - psiresp/tests
  utils:
    - psiresp/utils/due.py