language: generic
os: linux

env:
  global:
    - PYTEST_FLAGS="--disable-pytest-warnings --durations=50 -m fast"
    - PYTEST_LIST="tests"
    - MAIN_CMD="pytest ${PYTEST_LIST}"
    - SETUP_CMD="${PYTEST_FLAGS}"
    - BUILD_CMD="pip install -e ."
    - CONDA_ENVIRONMENT="devtools/conda-envs/test_env.yaml"
    - CONDA_CHANNEL_PRIORITY=True
    - PIP_DEPENDENCIES="duecredit"

  matrix:
    - CODECOV="true" SETUP_CMD="${PYTEST_FLAGS} --cov=psiresp"

stages:
  - build_and_test
  - name: deploy
    if: branch = master

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  fast_finish: true
  allow_failures:
    - env: NAME="linux_2.7_fast"
           PYTHON_VERSION=2.7
    - os: osx
      env: NAME="OSX_2.7_fast"
           PYTHON_VERSION=2.7


  include:
    # Extra includes for OSX since python language is not available by default on OSX
    # only run fast tests; optimize and RESP2 tests will time out
    - stage: build_and_test
    - env: NAME="linux_3.7_not_slow"
           PYTHON_VERSION=3.7
           PYTEST_FLAGS="--disable-pytest-warnings --durations=50 -m 'not slow'"
           CODECOV="true"
    - env: NAME="linux_3.8_fast"
           PYTHON_VERSION=3.8
    - env: NAME="linux_3.7_fast"
           PYTHON_VERSION=3.7
    - env: NAME="linux_3.6_fast"
           PYTHON_VERSION=3.6
    - env: NAME="Docs"
            SETUP_CMD="build_sphinx"
            PYTHON_VERSION=3.7
            MAIN_CMD="python setup.py"
            SETUP_CMD="build_sphinx"
            BUILD_DOCS=true
            BUILD_CMD="python setup.py install"
            CONDA_DEPENDENCIES="${CONDA_DEPENDENCIES} sphinx==1.8.5"
            PIP_DEPENDENCIES="${PIP_DEPENDENCIES} sphinx-sitemap sphinx_rtd_theme"
    - os: osx
      env: NAME="OSX_3.8_fast"
           PYTHON_VERSION=3.8
    - os: osx
      env: NAME="OSX_3.7_fast"
           PYTHON_VERSION=3.7
    - os: osx
      env: NAME="OSX_3.6_fast"
           PYTHON_VERSION=3.6

    - stage: deploy
      # name: Docs
      env: SETUP_CMD="build_sphinx"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
          python: "3.6"
        project_name: psiresp
        local_dir: docs/build

before_install:
  # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a
  # Install the Python environment
  # - source devtools/travis-ci/before_install.sh
  # - python -V

install:
  #   # Create test environment for package
  # - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VERSION devtools/conda-envs/test_env.yaml
  #   # Activate the test environment
  # - conda activate test
  #   # Build and install package
  # - python setup.py develop --no-deps
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - conda list
  - eval $BUILD_CMD

script:
  # - pytest -v --cov=psiresp tests/
  - cd ${TRAVIS_BUILD_DIR}
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ulimit -S -n 2048; fi
  - echo $MAIN_CMD $SETUP_CMD
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install pytest; fi
  - eval $MAIN_CMD $SETUP_CMD

after_success:
  - if [[ $CODECOV == 'true' ]]; then codecov; fi
