language: generic
os: linux

env:
  global:
    - PYTEST_FLAGS="-v --disable-pytest-warnings --durations=50"
    - PYTEST_SEL="-m fast"
    - BUILD_CMD="python setup.py develop --no-deps"
    - CONDAENV="test_env"

  matrix:
    - CODECOV="true" SETUP_CMD="${PYTEST_FLAGS} --cov=psiresp"

stages:
  - build_and_test
  - name: deploy
    if: branch = master

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  fast_finish: true
  allow_failures:
    - env: NAME="linux_2.7_fast"
    - env: NAME="OSX_2.7_fast"
    - env: NAME="OSX_3.8_fast"  # just hangs after duecredit installs?


  include:
    # Extra includes for OSX since python language is not available by default on OSX
    # only run fast tests; optimize and RESP2 tests will time out
    - stage: build_and_test
    - env: NAME="linux_3.7_not_slow"
           PYTHON_VERSION=3.7
           PYTEST_SEL="-m 'not slow'"
           CODECOV="true"
    - env: NAME="linux_3.8_fast"
           PYTHON_VERSION=3.8
    - env: NAME="linux_3.7_fast"
           PYTHON_VERSION=3.7
    - env: NAME="linux_3.6_fast"
           PYTHON_VERSION=3.6
    - env: NAME="Docs"
           BUILD_CMD="python setup.py build_sphinx"
           PYTHON_VERSION=3.7
           CONDAENV="docs_env"
    - env: NAME="linux_2.7_fast"
           PYTHON_VERSION=2.7
    - os: osx
      env: NAME="OSX_2.7_fast"
           PYTHON_VERSION=2.7
    - os: osx
      env: NAME="OSX_3.8_fast"
           PYTHON_VERSION=3.8
    - os: osx
      env: NAME="OSX_3.7_fast"
           PYTHON_VERSION=3.7
    - os: osx
      env: NAME="OSX_3.6_fast"
           PYTHON_VERSION=3.6

    - stage: deploy
      # name: Docs
      env: BUILD_CMD="python setup.py build_sphinx"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
          python: "3.6"
        project_name: psiresp
        local_dir: docs/build

before_install:
  # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a
  # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
  #   # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VERSION devtools/conda-envs/${CONDAENV}.yaml
  #   # Activate the test environment
  - conda activate test
  #   # Build and install package
  - eval $BUILD_CMD
  - conda list

script:
  - pytest ${PYTEST_FLAGS} ${PYTEST_SEL} tests/
  - cd ${TRAVIS_BUILD_DIR}
  # - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then ulimit -S -n 2048; fi
  # - echo $MAIN_CMD $SETUP_CMD
  # - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip install pytest; fi
  # - eval $MAIN_CMD $SETUP_CMD

after_success:
  - codecov
