language: generic
os: linux

env:
  global:
    - PYTEST_FLAGS="-v --disable-pytest-warnings --durations=50"
    - PYTEST_SEL="-m fast"
    - BUILD_CMD="python setup.py develop --no-deps"
    - CODECOV=""
    - CONDAENV="test_env"
    - PYTHON_VERSION=3.7

# Run jobs on container-based infrastructure, can be overridden per job

matrix:
  fast_finish: true
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    # only run fast tests; optimize and RESP2 tests will time out
    - env: NAME="linux_3.7_not_slow"
           PYTHON_VERSION=3.7
           PYTEST_SEL="-m 'not slow'"
           CODECOV="--cov=psiresp"
    # - env: NAME="linux_3.8_fast"  # currently incompatible
    #        PYTHON_VERSION=3.8
    - env: NAME="linux_3.6_fast"
           PYTHON_VERSION=3.6
    - env: NAME="Docs"
           BUILD_CMD="python setup.py build_sphinx"
           PYTHON_VERSION=3.7
           CONDAENV="docs_env"
    - os: osx
      env: NAME="OSX_3.7_fast"
           PYTHON_VERSION=3.7
    - os: osx
      env: NAME="OSX_3.6_fast"
           PYTHON_VERSION=3.6
           
before_install:
  # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a
  # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
  #   # Create test environment for package
  - python devtools/scripts/create_conda_env.py -n=test -p=$PYTHON_VERSION devtools/conda-envs/${CONDAENV}.yaml
  #   # Activate the test environment
  - conda activate test
  #   # Build and install package
  - echo $BUILD_CMD
  - eval $BUILD_CMD
  - conda list

script:
  - RUN_CMD="pytest ${PYTEST_FLAGS} ${PYTEST_SEL} ${CODECOV} tests/"
  - echo $RUN_CMD
  - eval $RUN_CMD

after_success:
  - codecov
