from .base import Model

class RespJob(Model):
    geometry_optimization_options: ...
    esp_generation_options: ...

    grid_generation_options: ...
    resp_fitting_options: ...

    structure_generation_options: ...
    

